#!/bin/sh -e
working_dir=~/.git-build
install_dir=/usr/local
version=$1

download_git() {
  curl -LO https://github.com/git/git/archive/v${version}.tar.gz
  tar zxf v${version}.tar.gz
  rm v${version}.tar.gz
  cd git-${version}
}

build_git() {
  make prefix=${install_dir} all
}

install_git() {
  sudo make prefix=${install_dir} install
}

if [ "$version" == "" ]; then
  echo 'usage: git install <version>'
  exit 1
fi

mkdir -p ${working_dir}
cd ${working_dir}

download_git
build_git
install_git
